project:
  type: website
  output-dir: docs 

website:
   navbar:
    logo: outil_R.PNG
    collapse-below: lg
    right:
      - text: "R"
        href: R/index.qmd
        menu:
          - text: "Nuage de mots avec RTemis"
            href: R/Nuage_de_mot/nuage_de_mot_rtemis.qmd
          - text: "Appliquer une même fonction à chaque élément d'un ensemble avec Purrr"
            href: R/Package_purrr/package_purrr.qmd
          - text: "Comment manipuler les données avec Dplyr"
            href: R/Package_dplyr/quarto_dplyr.qmd
          - text: "Package rio"
            href: R/Package_rio/Rio_package.qmd
          - text: "Produire des cartes thématiques avec Mapsf"
            href: R/Package_mapsf/map_sf.qmd
          - text: "Afficher des cartes interactives avec Mapview"
            href: R/Package_mapsf/R_cartographie.qmd
    


format:
  html:
    theme: [lux, sms.scss]
    css: sms.css
    toc: true
    logo-size: 100px
    grid:
     sidebar-width: 800px
     body-width:    800px
     margin-width:  100px
    code-line-numbers: true
    code-copy: true
    code-tools:
      source: true
highlight-style: dracula

   

