project:
  type: website
  output-dir: docs 

website:
  title: "Stage-1A-INED-COTTET"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Cartographie.qmd

format:
  html:
    theme: minimal
    css: styles.css
    toc: true


